template = "./template"

[app]
path = "/apps"
eslintrc = ".eslintrc.yaml"
tsconfig = "tsconfig.json"

[app.component]
dir = "components"
file_name = "index"

[lib]
path = "/packages"
version = "workspace:*"
